version: "3"
services:
  ganache:
    image: trufflesuite/ganache:latest
    container_name: ganache
    ports:
      - "8545:8545"   # Expose Ganache's RPC port
    volumes:
      - ganache_data:/root/.ganache
    environment:
      - GANACHE_MNEMONIC='candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'
      - GANACHE_NETWORK_ID=5777

  app:
    build: .  # This will point to the directory where you have your smart contract code and Node.js deployment code
    container_name: smart-contract-deployer
    depends_on:
      - ganache
    environment:
      - RPC_URL=http://ganache:8545  # Use the Ganache container's internal hostname
    command: ["node", "deployContractStoreString"]

volumes:
  ganache_data: